### ISSUE TITLE
Fasta output is broken

### ISSUE THREAD

**Issue by tanaes** [SamStudio8/dehumanizer#3]
Tried a dehumanizer 'polish' with reticulatus, but it broke downstream minimapping. 

Turns out, on inspection, the output files looked like:

```
@contig_1:1.0-13849.0
AAAATGATGCCGCGCAGCTCCC...
+
None
```

**Comment by SamStudio8** [comment]
Well that's pretty embarrassing! I know exactly how it happened - I needed
to rig it to do some reads at short notice and I hadn't finished
integrating it into reticulatus either...

Great spot and thanks for the PR - I'll accept when I get onto a real
computer!

**Comment by SamStudio8** [comment]
Fixed by #4
