### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by mattdmem** [SamStudio8/dehumanizer#6]
not sure why I'm submitting this as an issue because I literally have no more information other than I tried to run and got:

`Segmentation fault`

`dehumanise /data/md1mpar/wc/dehumanizer/manifest.txt --bam SHEF-C243B.bam --preset map-ont -o SHEF-C243B-clean.bam --log SHEF-C243B-clean.bam.log`

worked with a fastq, so maybe a problem with my bam?

**Comment by SamStudio8** [comment]
Does the BAM pass samtools quickcheck? Under the hood it's just spawning a
bunch of minimap threads, if it persists, try running it again with htop
and see if anything funny is going on?

**Comment by mattdmem** [comment]
working, must have been something about the configuration of the machine I was on. quickcheck passed. Can now do bam or fastq input.
