### ISSUE TITLE
Manifest download problem

### ISSUE THREAD

**Issue by embatty** [SamStudio8/dehumanizer#7]
I tried to download the pre-build manifests, but I ran into a couple of problems: first I get a warning that sam.s3.climb.ac.uk certificate has expired, then if I ignore the warning I get a 403 forbidden error. Is there somewhere else I can get them?

**Comment by SamStudio8** [comment]
Hi @embatty, the downloads have been removed as I've been changing how the database works but haven't finished the new implementation yet. I'm only supporting this tool internally at CLIMB-COVID at the moment.
