### ISSUE TITLE
Error 403 on wget of index

### ISSUE THREAD

**Issue by flashton2003** [SamStudio8/dehumanizer#8]
Hello,

I'm following the instructions and running the below command:

`wget https://sam.s3.climb.ac.uk/dehumanizer/20210906/dehuman.20210906.map-ont.mmi`

However, it's returning the below error:

```--2021-12-02 12:16:29--  https://sam.s3.climb.ac.uk/dehumanizer/20210906/dehuman.20210906.map-ont.mmi
Resolving sam.s3.climb.ac.uk (sam.s3.climb.ac.uk)... 137.205.52.6
Connecting to sam.s3.climb.ac.uk (sam.s3.climb.ac.uk)|137.205.52.6|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-12-02 12:16:30 ERROR 403: Forbidden.```

I've also tried with curl, which didn't work, and from multiple different servers. I think the problem is on your end?

Thanks,

Phil

**Comment by SamStudio8** [comment]
Hi @flashton2003, sorry for the trouble - the downloads have been removed as I've been changing how the database works but haven't finished the new implementation yet. I'm only supporting this tool internally at CLIMB-COVID at the moment. I'll update the README.

**Comment by flashton2003** [comment]
Ok, thanks for the info Sam.
